services:
  app:
    image: node:14-alpine
    command: sh -c "yarn install && yarn dev"
    depends_on:
      - mysql
    environment:
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_HOST: $MYSQL_HOST
      JWT_SECRET_KEY: $JWT_SECRET_KEY
    ports:
      - '3000:3000'
    working_dir: /app
    volumes:
      - ./:/app
  mysql:
    image: mysql:8
    restart: always
    volumes:
      - todos-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
volumes:
  todos-mysql:
