services:
  app:
    image: node:14-alpine
    command: sh -c "yarn install && yarn dev"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: todos
      MYSQL_HOST: mysql
    ports:
      - '3000:3000'
    working_dir: /app
    volumes:
      - ./:/app
  mysql:
    image: mysql:8
    restart: always
    volumes:
      - todos-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
volumes:
  todos-mysql:
