services:
  app:
    image: node:14-alpine
    command: sh -c "yarn install && yarn dev"
    depends_on:
      - postgres
    environment:
      NODE_ENV: $NODE_ENV
      PG_USER: $PG_USER
      PG_PASSWORD: $PG_PASSWORD
      PG_DB: $PG_DB
      PG_HOST: $PG_HOST
      JWT_SECRET_KEY: $JWT_SECRET_KEY
    ports:
      - '3000:3000'
    working_dir: /app
    volumes:
      - ./:/app
  postgres:
    image: postgres:14-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgres/data
    environment:
      POSTGRES_PASSWORD: $PG_PASSWORD
      POSTGRES_USER: $PG_USER
      POSTGRES_DB: $PG_DB
volumes:
  db-data:
